version: '3.9'

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  config-server:
    image: o-stock/config-server:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
    environment:
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    networks:
      backend:
        aliases:
          - "config-server"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  eureka-server:
    image: o-stock/eureka-server:0.0.1-SNAPSHOT
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - "8070:8070"
    environment:
      PROFILE: "default"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    networks:
      backend:
        aliases:
          - "eureka-server"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8070/actuator/health" ]
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 5s

  licensing-service:
    image: o-stock/licensing-service:0.0.2-SNAPSHOT
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    networks:
      backend:
        aliases:
          - "license-service"

  organization-service:
    image: o-stock/organization-service:0.0.1-SNAPSHOT
    depends_on:
      database:
        condition: service_healthy
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    ports:
      - "8079:8079"
    environment:
      PROFILE: "dev"
      CONFIGSERVER_URI: "http://config-server:8071"
      CONFIGSERVER_PORT: "8071"
      ENCRYPT_KEY: ${ENCRYPT_KEY}
    networks:
      backend:
        aliases:
          - "organization-service"

networks:
  backend:
    driver: bridge